"""Build the real-screenshot set for the landing page.

Sources: six genuine 1600x1200 captures of the shipped OraxRecordly app in
public/images/app/app-0N.jpg.

Outputs
-------
* public/images/app/app-0N.jpg  (4:3, used as-is by the editorial grid)
* public/images/app/app-0N-p.jpg (5:7 portrait cover-crop for the marquee)
* src/lib/lqip.ts               (tiny blur placeholders for both sets)

Nothing is ever stretched: the portrait variants are *cropped*, and where the
source is mostly empty space (the floating HUD, the region overlay) the crop is
centred on the real content.
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "public" / "images" / "app"

# (source, portrait crop left offset in px).  Portrait width for a 1200px-tall
# 5:7 frame is 857px; the offset slides that window over the 1600px source.
PORTRAIT_OFFSETS = {
    "app-01": 400,  # float the recording HUD bar (x 408..1230) into frame
    "app-02": 371,  # centre — preview + start of the inspector
    "app-03": 371,  # centre — the two captured-shot cards
    "app-04": 371,  # centre — the region selection rectangle
    "app-05": 703,  # right — the image-editor tool palette survives
    "app-06": 743,  # right — the settings inspector survives
}

TARGET_H = 1200
TARGET_W = round(TARGET_H * 5 / 7)  # 857


def portrait(src: Path, offset: int) -> Image.Image:
    im = Image.open(src).convert("RGB")
    left = max(0, min(offset, im.width - TARGET_W))
    return im.crop((left, 0, left + TARGET_W, TARGET_H))


def lqip(im: Image.Image) -> str:
    """A ~450 byte blurred JPEG standing in for the real file."""
    w = 12
    h = max(1, round(w * im.height / im.width))
    small = im.resize((w, h), Image.LANCZOS)
    buf = io.BytesIO()
    small.save(buf, "JPEG", quality=35)
    return "data:image/jpeg;base64," + base64.b64encode(buf.getvalue()).decode()


def main() -> None:
    entries: list[tuple[str, str]] = []

    for stem, offset in PORTRAIT_OFFSETS.items():
        src = APP / f"{stem}.jpg"
        im = Image.open(src).convert("RGB")
        assert im.size == (1600, 1200), (src, im.size)

        # grid slot — the source is already exactly 4:3, so it is used as-is
        # (no re-encode: the real captures keep their original pixels)
        grid_name = f"{stem}.jpg"

        # marquee slot — portrait cover crop
        port = portrait(src, offset)
        port_name = f"{stem}-p.jpg"
        port.save(APP / port_name, "JPEG", quality=86, optimize=True, progressive=True)

        entries.append((f"/images/app/{grid_name}", lqip(im)))
        entries.append((f"/images/app/{port_name}", lqip(port)))
        print(f"{stem}: grid {im.size}  portrait {port.size} offset={offset}")

    lines = [
        "/** Auto-generated by scripts/make-app-images.py — tiny blur placeholders. */",
        "export const LQIP: Record<string, string> = {",
    ]
    for path, data in entries:
        lines.append(f'  "{path}": "{data}",')
    lines.append("};")
    lines.append("")
    (ROOT / "src" / "lib" / "lqip.ts").write_text("\n".join(lines), encoding="utf-8")
    print(f"\nwrote src/lib/lqip.ts with {len(entries)} entries")


if __name__ == "__main__":
    main()
